"""
Django settings for sc_webui project.
Generated by 'django-admin startproject' using Django 2.1.2.
For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "@1#r=j%6k+d$*be6d@$&sxm@sa53s#^xkj_p+g=_a7vvt(2g*9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "cron.apps.CronConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "edge_cron.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": [],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_L10N = True

USE_TZ = False
# https://docs.djangoproject.com/ja/2.1/topics/i18n/timezones/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[%(server_time)s] %(message)s a",
        },
        "text_format": {
            "format": "%(asctime)s [PID: %(process)d][Thread ID: %(thread)d][%(levelname)s][%(name)s] %(message)s",
            "datefmt": "%Y/%m/%d %H:%M:%S",
        },
        "text_format2": {
            "format": "%(asctime)s [%(levelname)s][%(name)s] %(pathname)s(%(lineno)s) fn=%(funcName)s %(message)s",
            "datefmt": "%Y/%m/%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
        },
        "edge_cron_log": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": "/var/log/ot_tools/edge_cron.log",
            "when": "midnight",
            # 'interval': 1,
            "formatter": "text_format",
        },
        "edge_complete_to_archives_log": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": "/var/log/ot_tools/edge_complete_to_archives.log",
            "when": "midnight",
            # 'interval': 1,
            "formatter": "text_format",
        },
        "edge_send_version_log": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": "/var/log/ot_tools/edge_send_version.log",
            "when": "midnight",
            # 'interval': 1,
            "formatter": "text_format",
        },
    },
    "loggers": {
        "edge_cron": {
            "handlers": ["edge_cron_log"],
            "FIELD3": "edge_cron",
            "level": "DEBUG",
            "propagate": False,
        },
        "edge_complete_to_archives": {
            "handlers": ["edge_complete_to_archives_log"],
            "FIELD3": "edge_complete_to_archives",
            "level": "DEBUG",
            "propagate": False,
        },
        "edge_send_version": {
            "handlers": ["edge_send_version_log"],
            "FIELD3": "edge_send_version",
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
