name: Hadolint
on: push
jobs:
  build:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          recursive: true
